from pathlib import Path
import zipfile

base = Path("/mnt/data/ozon-opportunity-finder")
(base / "agents").mkdir(parents=True, exist_ok=True)
(base / "core").mkdir(parents=True, exist_ok=True)
(base / "prompts").mkdir(parents=True, exist_ok=True)
(base / "data").mkdir(parents=True, exist_ok=True)
(base / "output").mkdir(parents=True, exist_ok=True)

files = {
    "requirements.txt": "openai\npandas\nopenpyxl\npython-dotenv\ntqdm\n",
    ".env.example": "DEEPSEEK_API_KEY=your_key_here\n",
    "config.py": '''SELLER_CONSTRAINTS = {
    "cross_border": True,
    "shipping_days": 30,
    "min_price_rub": 2000,
    "avoid_categories": ["clothing","shoes","electronic_parts","liquid"]
}
''',
    "main.py": '''print("Project scaffold created. Implement workflow here.")\n''',
    "agents/market_agent.py": '''from openai import OpenAI\n''',
    "core/loader.py": '''import pandas as pd\n''',
    "core/feature_engine.py": '''def calculate_market_features(row):\n    return {}\n''',
    "core/scoring_engine.py": '''def calculate_opportunity_score(*args):\n    return 0\n''',
    "core/ranking_engine.py": '''def build_rankings(df):\n    return {}\n''',
    "core/report_engine.py": '''pass\n''',
    "prompts/market_prompt.txt": "Ozon market analysis prompt template\n",
    "README.md": "# Ozon Opportunity Finder\\nProject scaffold generated by ChatGPT.\\n"
}

for rel, content in files.items():
    p = base / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")

zip_path = "/mnt/data/ozon-opportunity-finder.zip"
with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
    for f in base.rglob("*"):
        if f.is_file():
            z.write(f, f.relative_to(base))

print(zip_path)
